apiVersion: 0.2.0
environments:
  default:
    destination:
      namespace: obj
      server: https://testmlops--jiovishwam-dev-r-f91a8f-82b34e3f.hcp.centralindia.azmk8s.io:443
    k8sVersion: v1.7.0
    path: default
kind: ksonnet.io/app
name: ks-obj
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
