---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ksonnet.io/component: pets-pvc
  name: pets-pvc
  namespace: obj
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coco
    ksonnet.io/component: model1
  name: coco-v1
  namespace: obj
spec:
  selector:
    matchLabels:
      app: coco
  template:
    metadata:
      labels:
        app: coco
        version: v1
    spec:
      containers:
      - args:
        - --port=9000
        - --model_name=coco
        - --model_base_path=gs://kai-test2-models/object-detection
        command:
        - /usr/bin/tensorflow_model_server
        image: gcr.io/kubeflow-images-public/tensorflow-serving-1.8gpu:latest
        imagePullPolicy: IfNotPresent
        name: coco
        ports:
        - containerPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pets-model
    ksonnet.io/component: pets-model
  name: pets-model-v1
  namespace: obj
spec:
  selector:
    matchLabels:
      app: pets-model
  template:
    metadata:
      labels:
        app: pets-model
        version: v1
    spec:
      containers:
      - args:
        - --port=9000
        - --model_name=pets-model
        - --model_base_path=/mnt/exported_graphs/saved_model
        command:
        - /usr/bin/tensorflow_model_server
        image: tensorflow/serving:1.10.0
        imagePullPolicy: IfNotPresent
        name: pets-model
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /mnt
          name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfserving-mapping-coco-get
      prefix: /models/coco/
      rewrite: /
      method: GET
      service: coco.obj:8000
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfserving-mapping-coco-post
      prefix: /models/coco/
      rewrite: /model/coco:predict
      method: POST
      service: coco.obj:8000
  labels:
    app: coco
    ksonnet.io/component: model1
  name: coco
  namespace: obj
spec:
  ports:
  - name: grpc-tf-serving
    port: 9000
    targetPort: 9000
  - name: http-tf-serving-proxy
    port: 8000
    targetPort: 8000
  selector:
    app: coco
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfserving-mapping-pets-model-get
      prefix: /models/pets-model/
      rewrite: /
      method: GET
      service: pets-model.obj:8000
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfserving-mapping-pets-model-post
      prefix: /models/pets-model/
      rewrite: /model/pets-model:predict
      method: POST
      service: pets-model.obj:8000
  labels:
    app: pets-model
    ksonnet.io/component: pets-model
  name: pets-model
  namespace: obj
spec:
  ports:
  - name: grpc-tf-serving
    port: 9000
    targetPort: 9000
  - name: http-tf-serving-proxy
    port: 8000
    targetPort: 8000
  selector:
    app: pets-model
  type: ClusterIP
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ksonnet.io/component: create-pet-record-job
  name: create-pet-record-job
  namespace: obj
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --label_map_path=/models/research/object_detection/data/pet_label_map.pbtxt
        - --data_dir=/pets_data
        - --output_dir=/pets_data
        command:
        - python
        - /models/research/object_detection/dataset_tools/create_pet_tf_record.py
        image: lcastell/pets_object_detection
        imagePullPolicy: IfNotPresent
        name: create-tf-record
        volumeMounts:
        - mountPath: /pets_data
          name: pets-data
      restartPolicy: Never
      volumes:
      - name: pets-data
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ksonnet.io/component: decompress-data-job
  name: decompress-data-job-annotations
  namespace: obj
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - tar
        - --no-same-owner
        - -xzvf
        - /pets_data/annotations.tar.gz
        - -C
        - /pets_data
        image: ubuntu:16.04
        imagePullPolicy: IfNotPresent
        name: decompress-data
        volumeMounts:
        - mountPath: /pets_data
          name: pets-data
      restartPolicy: Never
      volumes:
      - name: pets-data
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ksonnet.io/component: decompress-data-job
  name: decompress-data-job-dataset
  namespace: obj
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - tar
        - --no-same-owner
        - -xzvf
        - /pets_data/images.tar.gz
        - -C
        - /pets_data
        image: ubuntu:16.04
        imagePullPolicy: IfNotPresent
        name: decompress-data
        volumeMounts:
        - mountPath: /pets_data
          name: pets-data
      restartPolicy: Never
      volumes:
      - name: pets-data
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ksonnet.io/component: decompress-data-job
  name: decompress-data-job-model
  namespace: obj
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - tar
        - --no-same-owner
        - -xzvf
        - /pets_data/faster_rcnn_resnet101_coco_2018_01_28.tar.gz
        - -C
        - /pets_data
        image: ubuntu:16.04
        imagePullPolicy: IfNotPresent
        name: decompress-data
        volumeMounts:
        - mountPath: /pets_data
          name: pets-data
      restartPolicy: Never
      volumes:
      - name: pets-data
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ksonnet.io/component: export-tf-graph-job
  name: export-tf-graph-job
  namespace: obj
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --input_type=image_tensor
        - --pipeline_config_path=/pets_data/faster_rcnn_resnet101_pets.config
        - --trained_checkpoint_prefix=/pets_data/train/model.ckpt-0
        - --output_directory=/pets_data/exported_graphs
        command:
        - python
        - /models/research/object_detection/export_inference_graph.py
        image: lcastell/pets_object_detection
        imagePullPolicy: IfNotPresent
        name: export-graph
        volumeMounts:
        - mountPath: /pets_data
          name: pets-data
      restartPolicy: Never
      volumes:
      - name: pets-data
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ksonnet.io/component: get-data-job
  name: get-data-job-annotations
  namespace: obj
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - wget
        - http://www.robots.ox.ac.uk/~vgg/data/pets/data/annotations.tar.gz
        - -P
        - /pets_data
        - --no-check-certificate
        image: inutano/wget
        imagePullPolicy: IfNotPresent
        name: get-data
        volumeMounts:
        - mountPath: /pets_data
          name: pets-data
      restartPolicy: Never
      volumes:
      - name: pets-data
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ksonnet.io/component: get-data-job
  name: get-data-job-config
  namespace: obj
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - wget
        - https://raw.githubusercontent.com/kubeflow/examples/master/object_detection/conf/faster_rcnn_resnet101_pets.config
        - -P
        - /pets_data
        - --no-check-certificate
        image: inutano/wget
        imagePullPolicy: IfNotPresent
        name: get-data
        volumeMounts:
        - mountPath: /pets_data
          name: pets-data
      restartPolicy: Never
      volumes:
      - name: pets-data
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ksonnet.io/component: get-data-job
  name: get-data-job-dataset
  namespace: obj
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - wget
        - http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz
        - -P
        - /pets_data
        - --no-check-certificate
        image: inutano/wget
        imagePullPolicy: IfNotPresent
        name: get-data
        volumeMounts:
        - mountPath: /pets_data
          name: pets-data
      restartPolicy: Never
      volumes:
      - name: pets-data
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ksonnet.io/component: get-data-job
  name: get-data-job-model
  namespace: obj
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - wget
        - http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_2018_01_28.tar.gz
        - -P
        - /pets_data
        - --no-check-certificate
        image: inutano/wget
        imagePullPolicy: IfNotPresent
        name: get-data
        volumeMounts:
        - mountPath: /pets_data
          name: pets-data
      restartPolicy: Never
      volumes:
      - name: pets-data
        persistentVolumeClaim:
          claimName: pets-pvc
---
apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  labels:
    ksonnet.io/component: tf-training-job
  name: tf-training-job
  namespace: obj
spec:
  tfReplicaSpecs:
    Master:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - --alsologtostderr
            - --pipeline_config_path=/pets_data/faster_rcnn_resnet101_pets.config
            - --train_dir=/pets_data/train
            command:
            - python
            - research/object_detection/legacy/train.py
            image: lcastell/pets_object_detection
            imagePullPolicy: Always
            name: tensorflow
            volumeMounts:
            - mountPath: /pets_data
              name: pets-data
            workingDir: /models
          restartPolicy: OnFailure
          volumes:
          - name: pets-data
            persistentVolumeClaim:
              claimName: pets-pvc
    Ps:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - --alsologtostderr
            - --pipeline_config_path=/pets_data/faster_rcnn_resnet101_pets.config
            - --train_dir=/pets_data/train
            command:
            - python
            - research/object_detection/legacy/train.py
            image: lcastell/pets_object_detection
            imagePullPolicy: Always
            name: tensorflow
            volumeMounts:
            - mountPath: /pets_data
              name: pets-data
            workingDir: /models
          restartPolicy: OnFailure
          volumes:
          - name: pets-data
            persistentVolumeClaim:
              claimName: pets-pvc
      tfReplicaType: PS
    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - --alsologtostderr
            - --pipeline_config_path=/pets_data/faster_rcnn_resnet101_pets.config
            - --train_dir=/pets_data/train
            command:
            - python
            - research/object_detection/legacy/train.py
            image: lcastell/pets_object_detection
            imagePullPolicy: Always
            name: tensorflow
            volumeMounts:
            - mountPath: /pets_data
              name: pets-data
            workingDir: /models
          restartPolicy: OnFailure
          volumes:
          - name: pets-data
            persistentVolumeClaim:
              claimName: pets-pvc
